# 🧹 Notebook 02: Data Cleaning and Validation

## Product Line Profitability & Margin Performance Analysis  
### Nassau Candy Distributor

---

## 🔷 Objective

The objective of this notebook is to clean, validate, and prepare the raw dataset for profitability analysis.

This notebook will focus on:

- Loading the raw dataset
- Checking dataset structure
- Validating missing values
- Checking duplicate records
- Standardizing text columns
- Cleaning product names
- Converting date columns
- Validating financial consistency
- Exporting a clean dataset for feature engineering

## Import Libraries

In [1]:
# Import required libraries

import pandas as pd
import numpy as np

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:,.2f}".format)

print("Libraries imported successfully.")

Libraries imported successfully.

## 🔷 1. Load Raw Dataset

We will load the raw dataset from the `data/raw` folder.

In [2]:
# Load raw dataset

file_path = "../data/raw/Nassau Candy Distributor.csv"

df = pd.read_csv(file_path)

print("Raw dataset loaded successfully.")
print("Shape:", df.shape)

Raw dataset loaded successfully.
Shape: (10194, 18)

## 🔷 2. Initial Data Validation

Before cleaning, we validate the dataset structure, data types, and basic integrity.

In [3]:
# Check dataset structure

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  object
 7   City            10194 non-null  object
 8   State/Province  10194 non-null  object
 9   Postal Code     10194 non-null  object
 10  Division        10194 non-null  object
 11  Region          10194 non-null  object
 12  Product ID      10194 non-null  object
 13  Product Name    10194 non-null  object
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), object(12)
memory usage: 1.4+ MB

In [4]:
# Check missing values

df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
dtype: int64

In [5]:
# Check duplicate rows

df.duplicated().sum()

np.int64(0)

## 🔷 3. Text Cleaning and Standardization

In this step, we clean text-based columns by:

- Removing leading and trailing spaces
- Standardizing formatting
- Ensuring consistency across categories

In [12]:
# Strip spaces from text columns

text_columns = [
    "Product Name",
    "Division",
    "City",
    "State/Province",
    "Region"
]

for col in text_columns:
    df[col] = df[col].str.strip()

print("Text columns cleaned successfully.")

Text columns cleaned successfully.

In [13]:
# Check unique values after cleaning

df["Division"].unique()

array(['Chocolate', 'Other', 'Sugar'], dtype=object)

In [14]:
df["Product Name"].unique()

array(['Wonka Bar - Milk Chocolate', 'Wonka Bar - Triple Dazzle Caramel',
       'Wonka Bar - Nutty Crunch Surprise',
       'Wonka Bar -Scrumdiddlyumptious', 'Wonka Bar - Fudge Mallows',
       'Wonka Gum', 'Kazookles', 'Lickable Wallpaper',
       'Fizzy Lifting Drinks', 'Laffy Taffy', 'SweeTARTS', 'Nerds',
       'Hair Toffee', 'Everlasting Gobstopper', 'Fun Dip'], dtype=object)

In [16]:
df["City"].unique()

array(['Houston', 'Naperville', 'Philadelphia', 'Henderson', 'Athens',
       'Los Angeles', 'Huntsville', 'Laredo', 'Springfield', 'Dover',
       'San Francisco', 'Mount Pleasant', 'Newark', 'Bossier City',
       'Roswell', 'Scottsdale', 'Jonesboro', 'Westland', 'Smyrna',
       'Miami', 'Toronto', 'Lafayette', 'Las Vegas', 'Rapid City',
       'Alexandria', 'San Diego', 'New York City', 'Detroit',
       'Mission Viejo', 'Green Bay', 'Saint Petersburg', 'Seattle',
       'Escondido', 'Romeoville', 'Chesapeake', 'Linden',
       'North Las Vegas', 'Columbia', 'Concord', 'Dallas', 'Chicago',
       'Lubbock', 'Arlington', 'Richmond', 'Woodstock', 'Moreno Valley',
       'El Paso', 'Medford', 'Columbus', 'Elmhurst', 'Wilmington',
       'Margate', 'Yonkers', 'Des Moines', 'Denver', 'Royal Oak',
       'Roseville', 'Calgary', 'Huntington Beach', 'Logan',
       'Jacksonville', 'Tampa', 'Raleigh', 'Lakeville', 'Jackson',
       'Burbank', 'Lakeland', 'Knoxville', 'Hamilton', 'Asheville',
       'Tucson', 'Portage', 'Greensboro', 'Delray Beach', 'Fresno',
       'Pomona', 'Albuquerque', 'Plano', 'Brownsville', 'Long Beach',
       'Apple Valley', 'Vallejo', 'Revere', 'Virginia Beach',
       'Dearborn Heights', 'Decatur', 'Lancaster', 'Mobile', 'Marietta',
       'Toledo', 'Glendale', 'Chandler', 'Lewiston', 'Great Falls',
       'Austin', 'Redondo Beach', 'Lodi', 'Bloomington', 'Baltimore',
       'San Jose', 'Troy', 'San Gabriel', 'Jamestown', 'Memphis',
       'Lake Charles', 'Rochester', 'Louisville', 'Appleton',
       'Middletown', 'San Antonio', 'Freeport', 'Lawrence', 'Kent',
       'Fort Worth', 'Watertown', 'Milwaukee', 'Franklin', 'Hialeah',
       'West Jordan', 'Oakland', 'Eau Claire', 'Akron', 'Cleveland',
       'Midland', 'San Marcos', 'Vancouver', 'Montreal', 'Bellevue',
       'Murray', 'Buffalo Grove', 'Little Rock', 'Lakewood', 'Orem',
       'Aurora', 'Peoria', 'Bristol', 'Harrisonburg', 'Mishawaka',
       'Hempstead', 'Halifax', 'Lawton', 'Waynesboro', 'Meriden',
       'Pueblo', 'Chester', 'Phoenix', 'Minneapolis', 'Salem',
       'Southaven', 'Cincinnati', 'Deltona', 'Plainfield', 'Palm Coast',
       'El Cajon', 'Buffalo', 'Hackensack', 'Niagara Falls',
       'League City', 'Sioux Falls', 'New Rochelle', 'Riverside', 'Omaha',
       'Atlanta', 'Draper', 'Apopka', 'Charlotte', 'Bangor',
       'Pleasant Grove', 'Texas City', 'Trenton', 'Vacaville',
       'Hollywood', 'Fairfield', 'Hampton', 'Saint Charles',
       'North Miami', 'Grand Rapids', 'Oceanside', 'Billings',
       'Owensboro', 'Santa Fe', 'Fayetteville', 'Bowling Green', 'Tulsa',
       'Oswego', 'Santa Clara', 'Pasco', 'Tyler', 'Macon', 'Lowell',
       'Greenville', 'Gresham', 'Clifton', 'Oxnard', 'Olathe', 'Cary',
       'Odessa', 'Tempe', 'Corpus Christi', 'Chula Vista', 'Garland',
       'Boca Raton', 'Mesquite', 'Clarksville', 'Boynton Beach', 'Reno',
       'Evanston', 'Durham', 'Edmonton', 'Indianapolis', 'Manteca',
       'Pasadena', 'Edmonds', 'Mount Vernon', 'Everett', 'Parma',
       'Beaumont', 'Montgomery', 'Texarkana', 'Newport News',
       'Rancho Cucamonga', 'Rock Hill', 'Fort Lauderdale', 'Garden City',
       'Cranston', 'Lorain', 'Avondale', 'Mason', 'Orange', 'Portland',
       'Medina', 'Irving', 'Nashville', 'Wausau', 'Redding', 'Reading',
       'Madison', 'Carrollton', 'Johnson City', 'Manhattan', 'Moorhead',
       'Cedar Hill', 'Des Plaines', 'Provo', 'Salt Lake City',
       'Coon Rapids', 'Monroe', 'Bolingbrook', 'Sacramento',
       'Saint Louis', "St. John's", 'Woonsocket', 'Brentwood', 'Utica',
       'Tigard', 'Skokie', 'Orlando', 'Clinton', 'Sandy Springs',
       'Moncton', 'Oklahoma City', 'Gilbert', 'Olympia', 'Mesa',
       'Caldwell', 'Marion', 'Florence', 'Grand Prairie', 'Thornton',
       'Port Arthur', 'Colorado Springs', 'Beverly', 'Anaheim',
       'Cottage Grove', 'Quebec City', 'Taylor', 'Charlottetown',
       'Providence', 'Baytown', 'Woodbury', 'Park Ridge', 'Bartlett',
       'Bozeman', 'West Palm Beach', 'Rome', 'Suffolk', 'Kenosha',
       'Perth Amboy', 'Hot Springs', 'Las Cruces', 'Sterling Heights',
       'Leominster', 'Altoona', 'Coppell', 'Bethlehem', 'New Castle',
       'Plantation', 'Chico', 'Lehi', 'Auburn', 'San Bernardino',
       'Thousand Oaks', 'Covington', 'Coral Springs', 'Normal', 'Lansing',
       'Spokane', 'Norwich', 'Norfolk', 'Farmington', 'Mcallen',
       'New Albany', 'Santa Maria', 'Daytona Beach', 'Washington',
       'Tinley Park', 'Allen', 'Cuyahoga Falls', 'Camarillo', 'Wilson',
       'Frankfort', 'Wichita', 'Haltom City', 'Manchester', 'Paterson',
       'Pocatello', 'Layton', 'East Point', 'Carol Stream', 'Holyoke',
       'Vineland', 'Amarillo', 'Bakersfield', 'Port Saint Lucie',
       'Highland Park', 'South Bend', 'Hattiesburg', 'Kirkwood', 'Boise',
       'Redmond', 'Eagan', 'Yucaipa', 'New Bedford', 'Allentown',
       'Murrieta', 'Bedford', 'Holland', 'Charlottesville', 'Tamarac',
       'La Quinta', 'Redlands', 'North Charleston', 'Lincoln Park',
       'Quincy', 'Dubuque', 'Broken Arrow', 'Rockford', 'Murfreesboro',
       'Bayonne', 'Cambridge', 'Hillsboro', 'Rockville', 'Warner Robins',
       'Ann Arbor', 'Santa Barbara', 'Noblesville', 'Orland Park',
       'Sparks', 'Salinas', 'Conway', 'Burlington', 'Helena', 'Lebanon',
       'Rio Rancho', 'Frisco', 'Morristown', 'Lake Elsinore',
       'Pembroke Pines', 'Champaign', 'Dearborn', 'Santa Ana',
       'Tallahassee', 'Temecula', 'Costa Mesa', 'Glenview',
       'Bullhead City', 'Lindenhurst', 'Superior', 'Dublin', 'Visalia',
       'Missoula', 'Gaithersburg', 'Longview', 'Westfield', 'Gulfport',
       'Atlantic City', 'Sierra Vista', 'Chattanooga', 'Belleville',
       'La Crosse', 'Round Rock', 'Andover', 'Milford', 'Harlingen',
       'Redwood City', 'Bryan', 'Malden', 'Littleton', 'Saint Peters',
       'Norman', 'Grapevine', 'Gastonia', 'Jefferson City',
       'San Clemente', 'Hesperia', 'Encinitas', 'Yuma', 'Waterbury',
       'Warwick', 'Passaic', 'Parker', 'Longmont', 'York', 'Broomfield',
       'Winnipeg', 'Pensacola', 'Hendersonville', 'West Allis', 'Kenner',
       'Davis', 'Edinburg', 'Fort Collins', 'Pharr', 'Sheboygan',
       'Englewood', 'Waco', 'Waukesha', 'Georgetown', 'Cedar Rapids',
       'Saint Paul', 'Thomasville', 'Wheeling', 'Stockton', 'Arvada',
       'Twin Falls', 'Laguna Niguel', 'Marlborough', 'Woodland', 'Regina',
       'Iowa City', 'La Porte', 'Lake Forest', 'Coral Gables',
       'The Colony', 'Marysville', 'Bridgeton', 'San Luis Obispo',
       'Conroe', 'Urbandale', 'Eugene', 'Cheyenne', 'Arlington Heights',
       'Carlsbad', 'Edmond', 'Montebello', 'Shelton', 'East Orange',
       'Overland Park', 'Hickory', 'San Angelo', 'Morgan Hill', 'Antioch',
       'Richardson', 'Fremont', 'Greenwood', 'Homestead', 'Torrance',
       'Goldsboro', 'Nashua', 'Deer Park', 'Tuscaloosa', 'Ormond Beach',
       'Keller', 'Hoover', 'Muskogee', 'Rogers', 'Pompano Beach',
       'Oak Park', 'New Brunswick', 'Greeley', 'Kissimmee', 'Sanford',
       'Danville', 'Westminster', 'Mansfield', 'Fargo', 'Laurel',
       'Bellingham', 'Missouri City', 'Pearland', 'Rochester Hills',
       'Maple Grove', 'Chapel Hill', 'Commerce City', 'Citrus Heights',
       'Pico Rivera', 'San Mateo', 'Waterloo', 'Elkhart', 'Loveland',
       'Inglewood', 'La Mesa', 'Modesto', 'Independence', 'Clovis',
       'Grand Island', 'Melbourne', 'Pine Bluff', 'Saint Cloud',
       'Miramar', 'Mentor', 'Meridian', 'Springdale', 'Sunnyvale',
       'Coachella', 'Aberdeen', 'Jupiter', 'Grove City', 'Elyria',
       'Hagerstown', 'Saginaw', 'College Station', 'Ontario', 'Renton',
       'Canton', 'Summerville', 'Gladstone', 'Whittier', 'Abilene',
       'Palatine', 'Port Orange', 'Danbury'], dtype=object)

In [18]:
df["State/Province"].unique()

array(['Texas', 'Illinois', 'Pennsylvania', 'Kentucky', 'Georgia',
       'California', 'Virginia', 'Delaware', 'South Carolina', 'Ohio',
       'Louisiana', 'Oregon', 'Arizona', 'Arkansas', 'Michigan',
       'Tennessee', 'Florida', 'Ontario', 'Indiana', 'Nevada',
       'South Dakota', 'New York', 'Wisconsin', 'Washington',
       'New Jersey', 'Missouri', 'North Carolina', 'Colorado', 'Alberta',
       'Utah', 'Minnesota', 'Mississippi', 'Iowa', 'New Mexico',
       'Massachusetts', 'Alabama', 'Idaho', 'Montana', 'Maryland',
       'Connecticut', 'New Hampshire', 'British Columbia', 'Quebec',
       'Nova Scotia', 'Oklahoma', 'Nebraska', 'Maine', 'Kansas',
       'Rhode Island', 'Newfoundland and Labrador', 'New Brunswick',
       'Prince Edward Island', 'District of Columbia', 'Vermont',
       'Manitoba', 'Saskatchewan', 'Wyoming', 'North Dakota',
       'West Virginia'], dtype=object)

In [19]:
df["Region"].unique()

array(['Interior', 'Atlantic', 'Gulf', 'Pacific'], dtype=object)

## 🔷 4. Product Name Standardization

In this step, we ensure that product names are fully standardized and consistent for accurate grouping and analysis.

This includes:

- Checking unique product count
- Verifying naming consistency
- Ensuring alignment with product categories

In [20]:
# Count unique products

df["Product Name"].nunique()

15

In [22]:
# Display all unique product names

df["Product Name"].unique()

array(['Wonka Bar - Milk Chocolate', 'Wonka Bar - Triple Dazzle Caramel',
       'Wonka Bar - Nutty Crunch Surprise',
       'Wonka Bar -Scrumdiddlyumptious', 'Wonka Bar - Fudge Mallows',
       'Wonka Gum', 'Kazookles', 'Lickable Wallpaper',
       'Fizzy Lifting Drinks', 'Laffy Taffy', 'SweeTARTS', 'Nerds',
       'Hair Toffee', 'Everlasting Gobstopper', 'Fun Dip'], dtype=object)

## 🔷 5. Date Conversion

In this step, we convert date columns into proper datetime format for further analysis.

In [26]:
# Convert date columns to datetime using day-first format

df["Order Date"] = pd.to_datetime(df["Order Date"], dayfirst=True)
df["Ship Date"] = pd.to_datetime(df["Ship Date"], dayfirst=True)

print("Date columns converted successfully.")

Date columns converted successfully.

In [29]:
# Verify the top rows of order date and ship date format 

df[["Order Date", "Ship Date"]].head()

  Order Date  Ship Date
0 2024-01-03 2026-06-30
1 2024-01-04 2026-07-01
2 2024-01-04 2026-07-01
3 2024-01-04 2026-07-01
4 2024-01-05 2026-07-05

In [30]:
df[["Order Date", "Ship Date"]].dtypes

Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

## 🔷 6. Financial Data Validation

In this step, we verify whether the financial data is consistent.

We check:
- Whether Gross Profit = Sales - Cost
- Ensure data integrity before analysis

In [31]:
# Check financial consistency

df["Profit Check"] = df["Sales"] - df["Cost"] - df["Gross Profit"]

df["Profit Check"].describe()

count   10,194.00
mean         0.00
std          0.00
min         -0.00
25%          0.00
50%          0.00
75%          0.00
max          0.00
Name: Profit Check, dtype: float64

In [32]:
# Count mismatched rows

(df["Profit Check"] != 0).sum()

np.int64(3809)

In [33]:
df[df["Profit Check"] != 0].head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Profit Check
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,0.00
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,0.00
3,4,US-2021-112326-CHO-SCR-58000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,0.00
9,10,US-2021-167199-CHO-MIL-31000,2024-01-06,2026-07-03,Standard Class,167199,United States,Henderson,Kentucky,42420,Chocolate,Gulf,CHO-MIL-31000,Wonka Bar - Milk Chocolate,13.00,4,8.44,4.56,0.00
10,11,US-2021-167199-CHO-MIL-31000,2024-01-06,2026-07-03,Standard Class,167199,United States,Henderson,Kentucky,42420,Chocolate,Gulf,CHO-MIL-31000,Wonka Bar - Milk Chocolate,3.25,1,2.11,1.14,0.00

In [34]:
df["Profit Check"].abs().max()

7.105427357601002e-15

In [35]:
# Correct mismatch check using tolerance

(df["Profit Check"].abs() > 1e-6).sum()

np.int64(0)

In [36]:
df[df["Profit Check"].abs() > 1e-6].head()

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Country/Region, City, State/Province, Postal Code, Division, Region, Product ID, Product Name, Sales, Units, Gross Profit, Cost, Profit Check]
Index: []

### Financial Validation:

- Profit calculation is consistent across dataset
- Minor floating-point differences observed due to computation precision
- No real financial mismatches found

## 🔷 7. Final Clean Dataset Preparation

In this step, we finalize the cleaned dataset by:

- Removing temporary validation columns
- Verifying final dataset structure
- Exporting the cleaned dataset for further analysis

In [37]:
# Remove temporary column

df.drop(columns=["Profit Check"], inplace=True)

print("Temporary columns removed.")

Temporary columns removed.

In [38]:
# Final dataset check

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  datetime64[ns]
 3   Ship Date       10194 non-null  datetime64[ns]
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  object
 7   City            10194 non-null  object
 8   State/Province  10194 non-null  object
 9   Postal Code     10194 non-null  object
 10  Division        10194 non-null  object
 11  Region          10194 non-null  object
 12  Product ID      10194 non-null  object
 13  Product Name    10194 non-null  object
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(10)
memory usage: 1.4+ MB

In [39]:
df.shape

(10194, 18)

In [40]:
# Export cleaned dataset

output_path = "../data/processed/cleaned_nassau_candy.csv"

df.to_csv(output_path, index=False)

print("Clean dataset exported successfully.")

Clean dataset exported successfully.